// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudbeaver
{
    [CloudbeaverResourceType("cloudbeaver:index:DatabaseConnectionSecret")]
    public partial class DatabaseConnectionSecret : global::Pulumi.CustomResource
    {
        [Output("database_connection_id")]
        public Output<string> Database_connection_id { get; private set; } = null!;

        [Output("entra_group_name")]
        public Output<string> Entra_group_name { get; private set; } = null!;

        [Output("project_id")]
        public Output<string> Project_id { get; private set; } = null!;

        [Output("team_id")]
        public Output<string> Team_id { get; private set; } = null!;


        /// <summary>
        /// Create a DatabaseConnectionSecret resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DatabaseConnectionSecret(string name, DatabaseConnectionSecretArgs args, CustomResourceOptions? options = null)
            : base("cloudbeaver:index:DatabaseConnectionSecret", name, args ?? new DatabaseConnectionSecretArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DatabaseConnectionSecret(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("cloudbeaver:index:DatabaseConnectionSecret", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/athumi-eu",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DatabaseConnectionSecret resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DatabaseConnectionSecret Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new DatabaseConnectionSecret(name, id, options);
        }
    }

    public sealed class DatabaseConnectionSecretArgs : global::Pulumi.ResourceArgs
    {
        [Input("database_connection_id", required: true)]
        public Input<string> Database_connection_id { get; set; } = null!;

        [Input("entra_group_name", required: true)]
        public Input<string> Entra_group_name { get; set; } = null!;

        [Input("project_id", required: true)]
        public Input<string> Project_id { get; set; } = null!;

        [Input("team_id", required: true)]
        public Input<string> Team_id { get; set; } = null!;

        public DatabaseConnectionSecretArgs()
        {
        }
        public static new DatabaseConnectionSecretArgs Empty => new DatabaseConnectionSecretArgs();
    }
}
