// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudbeaver
{
    public static class EnableUser
    {
        public static Task<EnableUserResult> InvokeAsync(EnableUserArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<EnableUserResult>("cloudbeaver:index:enableUser", args ?? new EnableUserArgs(), options.WithDefaults());

        public static Output<EnableUserResult> Invoke(EnableUserInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<EnableUserResult>("cloudbeaver:index:enableUser", args ?? new EnableUserInvokeArgs(), options.WithDefaults());

        public static Output<EnableUserResult> Invoke(EnableUserInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<EnableUserResult>("cloudbeaver:index:enableUser", args ?? new EnableUserInvokeArgs(), options.WithDefaults());
    }


    public sealed class EnableUserArgs : global::Pulumi.InvokeArgs
    {
        [Input("enabled", required: true)]
        public bool Enabled { get; set; }

        [Input("user_name", required: true)]
        public string User_name { get; set; } = null!;

        public EnableUserArgs()
        {
        }
        public static new EnableUserArgs Empty => new EnableUserArgs();
    }

    public sealed class EnableUserInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        [Input("user_name", required: true)]
        public Input<string> User_name { get; set; } = null!;

        public EnableUserInvokeArgs()
        {
        }
        public static new EnableUserInvokeArgs Empty => new EnableUserInvokeArgs();
    }


    [OutputType]
    public sealed class EnableUserResult
    {
        public readonly bool Enabled;
        public readonly string User_name;

        [OutputConstructor]
        private EnableUserResult(
            bool enabled,

            string user_name)
        {
            Enabled = enabled;
            User_name = user_name;
        }
    }
}
