// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudbeaver
{
    [CloudbeaverResourceType("cloudbeaver:index:ProjectMember")]
    public partial class ProjectMember : global::Pulumi.CustomResource
    {
        [Output("member_id")]
        public Output<string> Member_id { get; private set; } = null!;

        [Output("project_id")]
        public Output<string> Project_id { get; private set; } = null!;


        /// <summary>
        /// Create a ProjectMember resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProjectMember(string name, ProjectMemberArgs args, CustomResourceOptions? options = null)
            : base("cloudbeaver:index:ProjectMember", name, args ?? new ProjectMemberArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProjectMember(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("cloudbeaver:index:ProjectMember", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/athumi-eu",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProjectMember resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProjectMember Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ProjectMember(name, id, options);
        }
    }

    public sealed class ProjectMemberArgs : global::Pulumi.ResourceArgs
    {
        [Input("member_id", required: true)]
        public Input<string> Member_id { get; set; } = null!;

        [Input("project_id", required: true)]
        public Input<string> Project_id { get; set; } = null!;

        public ProjectMemberArgs()
        {
        }
        public static new ProjectMemberArgs Empty => new ProjectMemberArgs();
    }
}
