// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudbeaver;

import com.pulumi.cloudbeaver.Utilities;
import com.pulumi.cloudbeaver.inputs.EnableUserArgs;
import com.pulumi.cloudbeaver.inputs.EnableUserPlainArgs;
import com.pulumi.cloudbeaver.outputs.EnableUserResult;
import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import java.util.concurrent.CompletableFuture;

public final class CloudbeaverFunctions {
    public static Output<EnableUserResult> enableUser(EnableUserArgs args) {
        return enableUser(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<EnableUserResult> enableUserPlain(EnableUserPlainArgs args) {
        return enableUserPlain(args, InvokeOptions.Empty);
    }
    public static Output<EnableUserResult> enableUser(EnableUserArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("cloudbeaver:index:enableUser", TypeShape.of(EnableUserResult.class), args, Utilities.withVersion(options));
    }
    public static Output<EnableUserResult> enableUser(EnableUserArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("cloudbeaver:index:enableUser", TypeShape.of(EnableUserResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<EnableUserResult> enableUserPlain(EnableUserPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("cloudbeaver:index:enableUser", TypeShape.of(EnableUserResult.class), args, Utilities.withVersion(options));
    }
}
