// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudbeaver;

import com.pulumi.core.internal.Codegen;
import java.lang.String;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("cloudbeaver");
/**
 * The cloudbeaver endpoint to connect to.
 * 
 */
    public String endpoint() {
        return Codegen.stringProp("endpoint").config(config).require();
    }
/**
 * The cloudbeaver password to use.
 * 
 */
    public String password() {
        return Codegen.stringProp("password").config(config).require();
    }
/**
 * The cloudbeaver username to use.
 * 
 */
    public String username() {
        return Codegen.stringProp("username").config(config).require();
    }
}
