// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudbeaver;

import com.pulumi.cloudbeaver.DatabaseConnectionSecretArgs;
import com.pulumi.cloudbeaver.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import javax.annotation.Nullable;

@ResourceType(type="cloudbeaver:index:DatabaseConnectionSecret")
public class DatabaseConnectionSecret extends com.pulumi.resources.CustomResource {
    @Export(name="database_connection_id", refs={String.class}, tree="[0]")
    private Output<String> database_connection_id;

    public Output<String> database_connection_id() {
        return this.database_connection_id;
    }
    @Export(name="entra_group_name", refs={String.class}, tree="[0]")
    private Output<String> entra_group_name;

    public Output<String> entra_group_name() {
        return this.entra_group_name;
    }
    @Export(name="project_id", refs={String.class}, tree="[0]")
    private Output<String> project_id;

    public Output<String> project_id() {
        return this.project_id;
    }
    @Export(name="team_id", refs={String.class}, tree="[0]")
    private Output<String> team_id;

    public Output<String> team_id() {
        return this.team_id;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DatabaseConnectionSecret(java.lang.String name) {
        this(name, DatabaseConnectionSecretArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DatabaseConnectionSecret(java.lang.String name, DatabaseConnectionSecretArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DatabaseConnectionSecret(java.lang.String name, DatabaseConnectionSecretArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cloudbeaver:index:DatabaseConnectionSecret", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private DatabaseConnectionSecret(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cloudbeaver:index:DatabaseConnectionSecret", name, null, makeResourceOptions(options, id), false);
    }

    private static DatabaseConnectionSecretArgs makeArgs(DatabaseConnectionSecretArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DatabaseConnectionSecretArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/athumi-eu")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DatabaseConnectionSecret get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DatabaseConnectionSecret(name, id, options);
    }
}
