// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudbeaver;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class DatabaseConnectionSecretArgs extends com.pulumi.resources.ResourceArgs {

    public static final DatabaseConnectionSecretArgs Empty = new DatabaseConnectionSecretArgs();

    @Import(name="database_connection_id", required=true)
    private Output<String> database_connection_id;

    public Output<String> database_connection_id() {
        return this.database_connection_id;
    }

    @Import(name="entra_group_name", required=true)
    private Output<String> entra_group_name;

    public Output<String> entra_group_name() {
        return this.entra_group_name;
    }

    @Import(name="project_id", required=true)
    private Output<String> project_id;

    public Output<String> project_id() {
        return this.project_id;
    }

    @Import(name="team_id", required=true)
    private Output<String> team_id;

    public Output<String> team_id() {
        return this.team_id;
    }

    private DatabaseConnectionSecretArgs() {}

    private DatabaseConnectionSecretArgs(DatabaseConnectionSecretArgs $) {
        this.database_connection_id = $.database_connection_id;
        this.entra_group_name = $.entra_group_name;
        this.project_id = $.project_id;
        this.team_id = $.team_id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DatabaseConnectionSecretArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DatabaseConnectionSecretArgs $;

        public Builder() {
            $ = new DatabaseConnectionSecretArgs();
        }

        public Builder(DatabaseConnectionSecretArgs defaults) {
            $ = new DatabaseConnectionSecretArgs(Objects.requireNonNull(defaults));
        }

        public Builder database_connection_id(Output<String> database_connection_id) {
            $.database_connection_id = database_connection_id;
            return this;
        }

        public Builder database_connection_id(String database_connection_id) {
            return database_connection_id(Output.of(database_connection_id));
        }

        public Builder entra_group_name(Output<String> entra_group_name) {
            $.entra_group_name = entra_group_name;
            return this;
        }

        public Builder entra_group_name(String entra_group_name) {
            return entra_group_name(Output.of(entra_group_name));
        }

        public Builder project_id(Output<String> project_id) {
            $.project_id = project_id;
            return this;
        }

        public Builder project_id(String project_id) {
            return project_id(Output.of(project_id));
        }

        public Builder team_id(Output<String> team_id) {
            $.team_id = team_id;
            return this;
        }

        public Builder team_id(String team_id) {
            return team_id(Output.of(team_id));
        }

        public DatabaseConnectionSecretArgs build() {
            if ($.database_connection_id == null) {
                throw new MissingRequiredPropertyException("DatabaseConnectionSecretArgs", "database_connection_id");
            }
            if ($.entra_group_name == null) {
                throw new MissingRequiredPropertyException("DatabaseConnectionSecretArgs", "entra_group_name");
            }
            if ($.project_id == null) {
                throw new MissingRequiredPropertyException("DatabaseConnectionSecretArgs", "project_id");
            }
            if ($.team_id == null) {
                throw new MissingRequiredPropertyException("DatabaseConnectionSecretArgs", "team_id");
            }
            return $;
        }
    }

}
