// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudbeaver;

import com.pulumi.cloudbeaver.ProjectMemberArgs;
import com.pulumi.cloudbeaver.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import javax.annotation.Nullable;

@ResourceType(type="cloudbeaver:index:ProjectMember")
public class ProjectMember extends com.pulumi.resources.CustomResource {
    @Export(name="member_id", refs={String.class}, tree="[0]")
    private Output<String> member_id;

    public Output<String> member_id() {
        return this.member_id;
    }
    @Export(name="project_id", refs={String.class}, tree="[0]")
    private Output<String> project_id;

    public Output<String> project_id() {
        return this.project_id;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ProjectMember(java.lang.String name) {
        this(name, ProjectMemberArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ProjectMember(java.lang.String name, ProjectMemberArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ProjectMember(java.lang.String name, ProjectMemberArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cloudbeaver:index:ProjectMember", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ProjectMember(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cloudbeaver:index:ProjectMember", name, null, makeResourceOptions(options, id), false);
    }

    private static ProjectMemberArgs makeArgs(ProjectMemberArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ProjectMemberArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/athumi-eu")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ProjectMember get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ProjectMember(name, id, options);
    }
}
