// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudbeaver;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * The cloudbeaver endpoint to connect to.
     * 
     */
    @Import(name="endpoint", required=true)
    private Output<String> endpoint;

    /**
     * @return The cloudbeaver endpoint to connect to.
     * 
     */
    public Output<String> endpoint() {
        return this.endpoint;
    }

    /**
     * The cloudbeaver password to use.
     * 
     */
    @Import(name="password", required=true)
    private Output<String> password;

    /**
     * @return The cloudbeaver password to use.
     * 
     */
    public Output<String> password() {
        return this.password;
    }

    /**
     * The cloudbeaver username to use.
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return The cloudbeaver username to use.
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.endpoint = $.endpoint;
        this.password = $.password;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param endpoint The cloudbeaver endpoint to connect to.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(Output<String> endpoint) {
            $.endpoint = endpoint;
            return this;
        }

        /**
         * @param endpoint The cloudbeaver endpoint to connect to.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(String endpoint) {
            return endpoint(Output.of(endpoint));
        }

        /**
         * @param password The cloudbeaver password to use.
         * 
         * @return builder
         * 
         */
        public Builder password(Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password The cloudbeaver password to use.
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        /**
         * @param username The cloudbeaver username to use.
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The cloudbeaver username to use.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public ProviderArgs build() {
            if ($.endpoint == null) {
                throw new MissingRequiredPropertyException("ProviderArgs", "endpoint");
            }
            if ($.password == null) {
                throw new MissingRequiredPropertyException("ProviderArgs", "password");
            }
            if ($.username == null) {
                throw new MissingRequiredPropertyException("ProviderArgs", "username");
            }
            return $;
        }
    }

}
