// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/cloudbeaver/Cloudbeaver/sdk/go/Cloudbeaver/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The cloudbeaver endpoint to connect to.
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "cloudbeaver:endpoint")
}

// The cloudbeaver password to use.
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "cloudbeaver:password")
}

// The cloudbeaver username to use.
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "cloudbeaver:username")
}
