// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudbeaver.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;


public final class EnableUserArgs extends com.pulumi.resources.InvokeArgs {

    public static final EnableUserArgs Empty = new EnableUserArgs();

    @Import(name="enabled", required=true)
    private Output<Boolean> enabled;

    public Output<Boolean> enabled() {
        return this.enabled;
    }

    @Import(name="user_name", required=true)
    private Output<String> user_name;

    public Output<String> user_name() {
        return this.user_name;
    }

    private EnableUserArgs() {}

    private EnableUserArgs(EnableUserArgs $) {
        this.enabled = $.enabled;
        this.user_name = $.user_name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EnableUserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EnableUserArgs $;

        public Builder() {
            $ = new EnableUserArgs();
        }

        public Builder(EnableUserArgs defaults) {
            $ = new EnableUserArgs(Objects.requireNonNull(defaults));
        }

        public Builder enabled(Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public Builder user_name(Output<String> user_name) {
            $.user_name = user_name;
            return this;
        }

        public Builder user_name(String user_name) {
            return user_name(Output.of(user_name));
        }

        public EnableUserArgs build() {
            if ($.enabled == null) {
                throw new MissingRequiredPropertyException("EnableUserArgs", "enabled");
            }
            if ($.user_name == null) {
                throw new MissingRequiredPropertyException("EnableUserArgs", "user_name");
            }
            return $;
        }
    }

}
