// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudbeaver.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;


public final class EnableUserPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final EnableUserPlainArgs Empty = new EnableUserPlainArgs();

    @Import(name="enabled", required=true)
    private Boolean enabled;

    public Boolean enabled() {
        return this.enabled;
    }

    @Import(name="user_name", required=true)
    private String user_name;

    public String user_name() {
        return this.user_name;
    }

    private EnableUserPlainArgs() {}

    private EnableUserPlainArgs(EnableUserPlainArgs $) {
        this.enabled = $.enabled;
        this.user_name = $.user_name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EnableUserPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EnableUserPlainArgs $;

        public Builder() {
            $ = new EnableUserPlainArgs();
        }

        public Builder(EnableUserPlainArgs defaults) {
            $ = new EnableUserPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder enabled(Boolean enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder user_name(String user_name) {
            $.user_name = user_name;
            return this;
        }

        public EnableUserPlainArgs build() {
            if ($.enabled == null) {
                throw new MissingRequiredPropertyException("EnableUserPlainArgs", "enabled");
            }
            if ($.user_name == null) {
                throw new MissingRequiredPropertyException("EnableUserPlainArgs", "user_name");
            }
            return $;
        }
    }

}
