# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('cloudbeaver')


class _ExportableConfig(types.ModuleType):
    @property
    def endpoint(self) -> Optional[str]:
        """
        The cloudbeaver endpoint to connect to.
        """
        return __config__.get('endpoint')

    @property
    def password(self) -> Optional[str]:
        """
        The cloudbeaver password to use.
        """
        return __config__.get('password')

    @property
    def username(self) -> Optional[str]:
        """
        The cloudbeaver username to use.
        """
        return __config__.get('username')

