# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .database_connection import *
from .database_connection_secret import *
from .project import *
from .project_member import *
from .provider import *
from .team import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_cloudbeaver.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_cloudbeaver.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "cloudbeaver",
  "mod": "index",
  "fqn": "pulumi_cloudbeaver",
  "classes": {
   "cloudbeaver:index:DatabaseConnection": "DatabaseConnection",
   "cloudbeaver:index:DatabaseConnectionSecret": "DatabaseConnectionSecret",
   "cloudbeaver:index:Project": "Project",
   "cloudbeaver:index:ProjectMember": "ProjectMember",
   "cloudbeaver:index:Team": "Team"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "cloudbeaver",
  "token": "pulumi:providers:cloudbeaver",
  "fqn": "pulumi_cloudbeaver",
  "class": "Provider"
 }
]
"""
)
