// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudbeaver.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class EnableUserResult {
    private Boolean enabled;
    private String user_name;

    private EnableUserResult() {}
    public Boolean enabled() {
        return this.enabled;
    }
    public String user_name() {
        return this.user_name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(EnableUserResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean enabled;
        private String user_name;
        public Builder() {}
        public Builder(EnableUserResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.user_name = defaults.user_name;
        }

        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("EnableUserResult", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder user_name(String user_name) {
            if (user_name == null) {
              throw new MissingRequiredPropertyException("EnableUserResult", "user_name");
            }
            this.user_name = user_name;
            return this;
        }
        public EnableUserResult build() {
            final var _resultValue = new EnableUserResult();
            _resultValue.enabled = enabled;
            _resultValue.user_name = user_name;
            return _resultValue;
        }
    }
}
