// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DatabaseConnectionSecret extends pulumi.CustomResource {
    /**
     * Get an existing DatabaseConnectionSecret resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): DatabaseConnectionSecret {
        return new DatabaseConnectionSecret(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cloudbeaver:index:DatabaseConnectionSecret';

    /**
     * Returns true if the given object is an instance of DatabaseConnectionSecret.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DatabaseConnectionSecret {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DatabaseConnectionSecret.__pulumiType;
    }

    public readonly database_connection_id!: pulumi.Output<string>;
    public readonly entra_group_name!: pulumi.Output<string>;
    public readonly project_id!: pulumi.Output<string>;
    public readonly team_id!: pulumi.Output<string>;

    /**
     * Create a DatabaseConnectionSecret resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatabaseConnectionSecretArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.database_connection_id === undefined) && !opts.urn) {
                throw new Error("Missing required property 'database_connection_id'");
            }
            if ((!args || args.entra_group_name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'entra_group_name'");
            }
            if ((!args || args.project_id === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project_id'");
            }
            if ((!args || args.team_id === undefined) && !opts.urn) {
                throw new Error("Missing required property 'team_id'");
            }
            resourceInputs["database_connection_id"] = args ? args.database_connection_id : undefined;
            resourceInputs["entra_group_name"] = args ? args.entra_group_name : undefined;
            resourceInputs["project_id"] = args ? args.project_id : undefined;
            resourceInputs["team_id"] = args ? args.team_id : undefined;
        } else {
            resourceInputs["database_connection_id"] = undefined /*out*/;
            resourceInputs["entra_group_name"] = undefined /*out*/;
            resourceInputs["project_id"] = undefined /*out*/;
            resourceInputs["team_id"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DatabaseConnectionSecret.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a DatabaseConnectionSecret resource.
 */
export interface DatabaseConnectionSecretArgs {
    database_connection_id: pulumi.Input<string>;
    entra_group_name: pulumi.Input<string>;
    project_id: pulumi.Input<string>;
    team_id: pulumi.Input<string>;
}
