// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DatabaseConnection extends pulumi.CustomResource {
    /**
     * Get an existing DatabaseConnection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): DatabaseConnection {
        return new DatabaseConnection(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cloudbeaver:index:DatabaseConnection';

    /**
     * Returns true if the given object is an instance of DatabaseConnection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DatabaseConnection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DatabaseConnection.__pulumiType;
    }

    declare public readonly auth_model_id: pulumi.Output<string | undefined>;
    declare public readonly database: pulumi.Output<string>;
    declare public readonly driver_id: pulumi.Output<string | undefined>;
    declare public readonly endpoint: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly port: pulumi.Output<string | undefined>;
    declare public readonly project_id: pulumi.Output<string>;

    /**
     * Create a DatabaseConnection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatabaseConnectionArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.database === undefined && !opts.urn) {
                throw new Error("Missing required property 'database'");
            }
            if (args?.endpoint === undefined && !opts.urn) {
                throw new Error("Missing required property 'endpoint'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.project_id === undefined && !opts.urn) {
                throw new Error("Missing required property 'project_id'");
            }
            resourceInputs["auth_model_id"] = (args?.auth_model_id) ?? "azure_ad_postgresql";
            resourceInputs["database"] = args?.database;
            resourceInputs["driver_id"] = (args?.driver_id) ?? "postgresql:postgres-jdbc";
            resourceInputs["endpoint"] = args?.endpoint;
            resourceInputs["name"] = args?.name;
            resourceInputs["port"] = (args?.port) ?? "5432";
            resourceInputs["project_id"] = args?.project_id;
        } else {
            resourceInputs["auth_model_id"] = undefined /*out*/;
            resourceInputs["database"] = undefined /*out*/;
            resourceInputs["driver_id"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["project_id"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DatabaseConnection.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a DatabaseConnection resource.
 */
export interface DatabaseConnectionArgs {
    auth_model_id?: pulumi.Input<string>;
    database: pulumi.Input<string>;
    driver_id?: pulumi.Input<string>;
    endpoint: pulumi.Input<string>;
    name: pulumi.Input<string>;
    port?: pulumi.Input<string>;
    project_id: pulumi.Input<string>;
}
