// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ProjectMember extends pulumi.CustomResource {
    /**
     * Get an existing ProjectMember resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ProjectMember {
        return new ProjectMember(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cloudbeaver:index:ProjectMember';

    /**
     * Returns true if the given object is an instance of ProjectMember.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectMember {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectMember.__pulumiType;
    }

    declare public readonly member_id: pulumi.Output<string>;
    declare public readonly project_id: pulumi.Output<string>;

    /**
     * Create a ProjectMember resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectMemberArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.member_id === undefined && !opts.urn) {
                throw new Error("Missing required property 'member_id'");
            }
            if (args?.project_id === undefined && !opts.urn) {
                throw new Error("Missing required property 'project_id'");
            }
            resourceInputs["member_id"] = args?.member_id;
            resourceInputs["project_id"] = args?.project_id;
        } else {
            resourceInputs["member_id"] = undefined /*out*/;
            resourceInputs["project_id"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProjectMember.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ProjectMember resource.
 */
export interface ProjectMemberArgs {
    member_id: pulumi.Input<string>;
    project_id: pulumi.Input<string>;
}
